// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3TaTW4OCh8PCHA9nJy-68AOgulaba-t0',
    appId: '1:829618420464:web:4f55e329cfe8e04e16e035',
    messagingSenderId: '829618420464',
    projectId: 'pre-loved-marketplace',
    authDomain: 'pre-loved-marketplace.firebaseapp.com',
    storageBucket: 'pre-loved-marketplace.firebasestorage.app',
    measurementId: 'G-1HF4TK1WS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM_6XvpYCPtonvEXymytDSM2haxkJy1k4',
    appId: '1:829618420464:android:b169fafbede11e2316e035',
    messagingSenderId: '829618420464',
    projectId: 'pre-loved-marketplace',
    storageBucket: 'pre-loved-marketplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWMqC226MXPxY-RyQ7SC01GwNhuDqOqfg',
    appId: '1:829618420464:ios:2278a32146309fb816e035',
    messagingSenderId: '829618420464',
    projectId: 'pre-loved-marketplace',
    storageBucket: 'pre-loved-marketplace.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWMqC226MXPxY-RyQ7SC01GwNhuDqOqfg',
    appId: '1:829618420464:ios:2278a32146309fb816e035',
    messagingSenderId: '829618420464',
    projectId: 'pre-loved-marketplace',
    storageBucket: 'pre-loved-marketplace.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3TaTW4OCh8PCHA9nJy-68AOgulaba-t0',
    appId: '1:829618420464:web:9f4d7615a76d690916e035',
    messagingSenderId: '829618420464',
    projectId: 'pre-loved-marketplace',
    authDomain: 'pre-loved-marketplace.firebaseapp.com',
    storageBucket: 'pre-loved-marketplace.firebasestorage.app',
    measurementId: 'G-8E4R8G9ZCS',
  );
}
