import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';

import 'providers/product_provider.dart';
import 'providers/auth_provider.dart';
import 'providers/cart_provider.dart';
import 'providers/ThemeProvider.dart'; // Ensure the file is named theme_provider.dart
import 'providers/user_profile_provider.dart';

import 'screens/auth/login_screen.dart';
import 'screens/auth/signup_screen.dart';
import 'screens/main/home_screen.dart';
import 'screens/splash_screen.dart';
import 'screens/cart_screen.dart';
import 'screens/profile/user_profile_screen.dart';

import 'utils/themes.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => UserProfileProvider()),
        ChangeNotifierProvider(create: (_) => ProductProvider()),
        ChangeNotifierProvider(create: (_) => AppAuthProvider()),
        ChangeNotifierProvider(create: (_) => CartProvider()),
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
      ],
      child: Consumer2<AppAuthProvider, ThemeProvider>(
        builder: (context, authProvider, themeProvider, _) {
          return MaterialApp(
            title: 'Pre-Loved Marketplace',
            debugShowCheckedModeBanner: false,
            theme: AppTheme.lightTheme,
            darkTheme: AppTheme.darkTheme,
            themeMode: themeProvider.themeMode,
            home: const SplashScreen(),
            routes: {
              '/login': (context) => const LoginScreen(),
              '/signup': (context) => const SignupScreen(),
              '/home': (context) => const HomeScreen(),
              '/splash': (context) => const SplashScreen(),
              '/cart': (context) => const CartScreen(),
              '/profile': (context) => const UserProfileScreen(),
            },
            onGenerateRoute: (settings) {
              if (!authProvider.isLoggedIn &&
                  settings.name != '/login' &&
                  settings.name != '/signup') {
                return MaterialPageRoute(
                  builder: (context) => const LoginScreen(),
                );
              }

              if (authProvider.isLoggedIn &&
                  (settings.name == '/login' || settings.name == '/signup')) {
                return MaterialPageRoute(
                  builder: (context) => const HomeScreen(),
                );
              }

              return null;
            },
          );
        },
      ),
    );
  }
}
